version: 2
registries:
  codeartifact:
    type: npm-registry
    url: https://vero-020003075374.d.codeartifact.us-east-1.amazonaws.com/npm/npm/
    token: ${{secrets.CODEARTIFACT_AUTH_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    registries:
      - codeartifact
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: daily
